### ISSUE TITLE
Release notes for version 3?

### ISSUE THREAD

**Issue by rodrigoplant** [kikinteractive/app#72]
Hello,

We're currently developing an app using App.js structure. It's halfway done and we just noticed the update but couldn't find what's new on this version. Will there be a document with that?

Thanks.

**Comment by jairajs89** [comment]
V3 is not a major update, the main changes were to support Android L. We were forced to change the version due to some backwards incompatibilities.




* Android L transitions are supported by default

* The topbar UI uses the material design theme

* app-icon is no longer supported

* Dialogs have a new unified theme across OSs, no longer support custom choice responses

* Bugfixes




We've migrated a bunch of our apps with little fuss. Excessive topbar or dialog customisation are the only risk. I'd drop it in and see how that goes, else go back to V2.

**Comment by JSoon** [comment]
I used to use custom choice responses of dialog in my project with V2, but why V3 does not support it anymore, and how should i suppose to implement the choice sections? Thanks. @jairajs89

**Comment by jairajs89** [comment]
@JSoon [Here is a quick implementation](https://github.com/kikinteractive/app/issues/73#issuecomment-75089546)
